#!/usr/bin/env sh
#. "$(dirname -- "$0")/_/husky.sh"

if command -v npm.cmd >/dev/null 2>&1; then
  NPM_BIN=npm.cmd
else
  NPM_BIN=npm
fi

if [ -n "$CI" ]; then
  echo "Skipping pre-commit checks in CI environment."
else
  $NPM_BIN run lint
  $NPM_BIN run format
fi
